### ISSUE TITLE
SSIS Odata unable to cast object

### ISSUE THREAD

**Issue by OostAtGitHub** [OData/odataorg.github.io#258]
Situation is as follows.

1. created a SSIS package
2. added an Odata connection connected to Microsoft Dynamics CRM Online. Test was succesfull.
3. inserted an Odata Source component in the Data Flow
4. try to preview the Account collection (using collection) and then an error appearses. The message and technical details are below. What is wrong? Is it the data or perhaps a bug, I don't know. 

**Message**

TITLE: System.Data
------------------------------

Unable to cast object of type 'Microsoft.OData.Edm.Library.Date' to type 'System.IConvertible'.Couldn't store <2020-08-21> in hso_scribe_date Column.  Expected type is DateTime.

------------------------------
ADDITIONAL INFORMATION:

Unable to cast object of type 'Microsoft.OData.Edm.Library.Date' to type 'System.IConvertible'. (System.Data)

------------------------------
BUTTONS:

OK
------------------------------

**Technical details**
===================================

Unable to cast object of type 'Microsoft.OData.Edm.Library.Date' to type 'System.IConvertible'.Couldn't store <2020-08-21> in hso_scribe_date Column.  Expected type is DateTime. (System.Data)

------------------------------
Program Location:

   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataRow.set_Item(DataColumn column, Object value)
   at Microsoft.DataTransformationServices.DataFlowUI.ODataConnectionPage.PreviewButton_Click(Object sender, EventArgs e)

===================================

Unable to cast object of type 'Microsoft.OData.Edm.Library.Date' to type 'System.IConvertible'. (System.Data)

------------------------------
Program Location:

   at System.Data.Common.DateTimeStorage.Set(Int32 record, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)

**Comment by chaz-clark** [comment]
Same Issue:
Unable to cast object of type 'Microsoft.OData.Edm.Library.Date' to type 'System.IConvertible'.Couldn't store <2021-11-12> in LastAuditDate Column.  Expected type is DateTime. (System.Data)
